# Generated by Django 4.1.2 on 2022-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
