# Generated by Django 4.1.2 on 2022-11-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
    ]
